image: rust:1.59

pipelines:
  branches:
    '{master,develop}':
      - step:
          script:
            - echo "Update docker image"              ; apt update ; apt upgrade -y ; apt install libudev-dev -y
            - echo "Updates to rustup"                ; rustup self update
            - echo "Update Rust toolchain"            ; rustup update
            - echo "Add rustfmt"                      ; rustup component add rustfmt
            - echo "Check code format"                ; cargo fmt --all -- --check
            - echo "Build project"                    ; cargo build --release
            - echo "Build examples"                   ; cargo build --examples
            - echo "Run unit tests"                   ; cargo test --lib --release -v --no-fail-fast -- --nocapture --test
            - echo "Run documentation tests"          ; cargo test --doc --release -v --no-fail-fast -- --nocapture --test
