[package]
name = "wake"
version = "0.2.1"
authors = ["Vladimir K <ew1abz@gmail.com>"]

[dev-dependencies.serialport]
version = "3.3.0"
default-features = false

[dev-dependencies]
clap = "2.33.0"
rand = "0.7.3"
